FROM oven/bun:1

WORKDIR /app

COPY ./turbo.json ./turbo.json
COPY ./bun.lockb ./bun.lockb
COPY ./package.json ./package.json

COPY ./packages ./packages
COPY ./apps/web ./apps/web

RUN bun install

EXPOSE 3000

CMD ["bun", "dev:web"]
# docker build --build-arg PUBLISHABLE_KEY=<NEXT_PUBLIC> -t quiz_fe -f ./docker/Dockerfile.web .