FROM oven/bun:1

WORKDIR /app

COPY ./turbo.json ./turbo.json
COPY ./bun.lockb ./bun.lockb
COPY ./package.json ./package.json
 
COPY ./packages ./packages
COPY ./apps/backend ./apps/backend

RUN bun install
RUN bun db:generate

EXPOSE 8000

CMD ["bun", "dev:backend"]
# docker build -t quiz_be -f ./docker/Dockerfile.backend .